### PR TITLE
I deleted 3 files  also i fix the nav bar and the 2nd navbar

### PR DESCRIPTION
**Pull request by Gedwion**

### CODE REVIEW

**Comment by Gedwion** [comment]
I already fix the navbar and 2nd nav bar

**Comment by Gedwion** [comment]
I already fixed the navbar and 2nd navbar

**Review by mike489 — CHANGES_REQUESTED** [review]
cancel  the PR please and u and me will have a video chat

**Comment by Gedwion** [comment]
I just fixed it as you went and I sent a pull request
mike489/book_store_project
at Gedion-product-detail (github.com)
<https://github.com/mike489/book_store_project/tree/Gedion-product-detail> sent
a pull request on the previous repo
10 Q

**Pull request closed without merging**
